Additional output for diagnosing problems

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -1,5 +1,6 @@
 #! /bin/bash
 
+echo "Current OpenFOAM version is $WM_PROJECT_VERSION."
 if [ -e foamVersionThisIsCompiledFor ]; then
     prevVersion=$(<foamVersionThisIsCompiledFor)
     echo "Previously compiled for OpenFOAM ($prevVersion)"
@@ -58,6 +59,12 @@ if [ -z $SWAK_DO_NOT_GENERATE_NEW_VERSION_FILE ]; then
     ./maintainanceScripts/makeSwakVersionFile.py
 else
     echo "Not generating new version file because SWAK_DO_NOT_GENERATE_NEW_VERSION_FILE is set"
+fi
+mercurialVersion=$(hg id)
+if [ $? != 0 ]; then
+    echo "Could not get version of the sources"
+else
+    echo "hg info: $mercurialVersion"
 fi
 
 (cd Libraries; wmake all )
