Test for the existence of flex

diff --git a/Libraries/Allwmake b/Libraries/Allwmake
--- a/Libraries/Allwmake
+++ b/Libraries/Allwmake
@@ -8,6 +8,14 @@ if [[ $NOBISON != 0 ]]; then
     exit
 fi
 
+FLEXPATH=`which flex`
+NOFLEX=$?
+
+if [[ $NOFLEX != 0 ]]; then
+    echo "No 'flex' found. This is absolutely essential for swak4Foam. Can't go on"
+    exit
+fi
+
 BISONVER=`bison -V | head -n 1| tr ' ' '\n' | tail -n 1`
 
 echo "Bison is version $BISONVER"
